#
# Running `guard start` in the directory containing this file
# executes it in he proper way. Don't do `ruby Guardfile`.
#


require 'asciidoctor'
require 'erb'

guard 'shell' do
  watch(/^README\.adoc$/) {|m|
    Asciidoctor.convert_file(m[0], :in_place => true)
  }
end

#
# http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/
#
# Bear in mind that there are two different browser plugins:
#   - Asciidoc Live Preview
#   - LiveReaload
#
# The code just below works with the LiveReload browser plugin.

guard 'livereload' do
  watch(%r{^.+\.(css|js|html)$})
end

# vim:set filetype=ruby:
